name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up git submodules
        run: git submodule init && git submodule update
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - uses: burrunan/gradle-cache-action@v1
        name: Cache .gradle
        with:
          job-id: build
          arguments: build javadoc